[theme]
base = "light"
primaryColor = "#145C64"
backgroundColor = "#F7F5F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14213D"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true

[browser]
gatherUsageStats = false
